// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxUxDk1wOpg_ubozWnqUuXUo-pkvHF7us',
    appId: '1:397805657842:web:1becdbeb0a97844d0bfa6b',
    messagingSenderId: '397805657842',
    projectId: 'monitoring-suhu-b3682',
    authDomain: 'monitoring-suhu-b3682.firebaseapp.com',
    databaseURL: 'https://monitoring-suhu-b3682-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoring-suhu-b3682.firebasestorage.app',
    measurementId: 'G-38VJ0HTHJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_vtjjfGHt2ckE1icwC3gpcY2SjNyoNzc',
    appId: '1:397805657842:android:8ddee3fd86cd20b00bfa6b',
    messagingSenderId: '397805657842',
    projectId: 'monitoring-suhu-b3682',
    databaseURL: 'https://monitoring-suhu-b3682-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoring-suhu-b3682.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSOJxBeWrBeUFjtZmepTf43_Qntf06_N4',
    appId: '1:397805657842:ios:aa4b19610e748c7d0bfa6b',
    messagingSenderId: '397805657842',
    projectId: 'monitoring-suhu-b3682',
    databaseURL: 'https://monitoring-suhu-b3682-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoring-suhu-b3682.firebasestorage.app',
    iosBundleId: 'com.example.monitoringSuhu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSOJxBeWrBeUFjtZmepTf43_Qntf06_N4',
    appId: '1:397805657842:ios:aa4b19610e748c7d0bfa6b',
    messagingSenderId: '397805657842',
    projectId: 'monitoring-suhu-b3682',
    databaseURL: 'https://monitoring-suhu-b3682-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoring-suhu-b3682.firebasestorage.app',
    iosBundleId: 'com.example.monitoringSuhu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxUxDk1wOpg_ubozWnqUuXUo-pkvHF7us',
    appId: '1:397805657842:web:218f1a1aa33890b60bfa6b',
    messagingSenderId: '397805657842',
    projectId: 'monitoring-suhu-b3682',
    authDomain: 'monitoring-suhu-b3682.firebaseapp.com',
    databaseURL: 'https://monitoring-suhu-b3682-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoring-suhu-b3682.firebasestorage.app',
    measurementId: 'G-X23TVDH8FB',
  );
}
